version: "3.8"

services:
  db2:
    image: ibmcom/db2:11.5.8.0
    container_name: db2-container
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=passw0rd
      - DBNAME=testdb
    ports:
      - "50000:50000"
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - db2data:/database

  batchops:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: batch-runner
    depends_on:
      - db2
    environment:
      - CONN_STR=DATABASE=testdb;HOSTNAME=db2;PORT=50000;PROTOCOL=TCPIP;UID=db2inst1;PWD=passw0rd;
    volumes:
      - ../jobs:/app/jobs
      - ../data:/app/data
      - ../.env:/app/.env
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  db2data: