version: "3.8"

services:
  db2:
    image: ibmcom/db2:11.5.8.0
    container_name: db2-container
    environment:
      - LICENSE=accept
      - DB2INST1=db2inst1
      - DB2INST1_PASSWORD=passw0rd
      - DB2FENC1=db2fenc1
      - DB2FENC1_PASSWORD=passw0rd
      - DBNAME=testdb
    ports:
      - "50000:50000"
    volumes:
      - db2data:/database
      - ./infra/init_public.sql:/database/config/init_public.sql
      - ./infra/init_job_mgmt.sql:/database/config/init_job_mgmt.sql
    tty: true
    stdin_open: true
    privileged: true  # Required by DB2 setup

volumes:
  db2data: