version: '3.8'

services:
  db2:
    image: ibmcom/db2:11.5.8.0
    container_name: db2-container
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=passw0rd
      - DBNAME=testdb
    ports:
      - "50000:50000"
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - db2data:/database

volumes:
  db2data: