-- Create schema
CREATE SCHEMA job_mgmt;

-- Create JOBS table
CREATE TABLE job_mgmt.JOBS (
    JOB_ID      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_NAME    VARCHAR(255),
    SCHEDULE    VARCHAR(255),
    IS_ACTIVE   BOOLEAN,
    CREATED_AT  TIMESTAMP
);

-- Create JOB_RUNS table
CREATE TABLE job_mgmt.JOB_RUNS (
    RUN_ID      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID      INTEGER NOT NULL,
    STARTED_AT  TIMESTAMP,
    ENDED_AT    TIMESTAMP,
    STATUS      VARCHAR(50),
    FOREIGN KEY (JOB_ID) REFERENCES job_mgmt.JOBS(JOB_ID)
);

-- Create JOB_LOGS table
CREATE TABLE job_mgmt.JOB_LOGS (
    LOG_ID      INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUN_ID      INTEGER NOT NULL,
    LOG_TIME    TIMESTAMP,
    MESSAGE     VARCHAR(1000),
    FOREIGN KEY (RUN_ID) REFERENCES job_mgmt.JOB_RUNS(RUN_ID)
);