apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-exports-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/job-exports"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""