apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-exports-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: job-exports-pv
  storageClassName: ""