apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scheduler-role 
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]